version: '3'

services:
    backend:
        container_name: flight_tracker_backend
        build:
            context: .
            dockerfile: src/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src:/usr/src/
        env_file: ./.env.dev
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:16
        container_name: postgres_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            DATABASE_NAME: postgres
            DATABASE_USER: postgres
            POSTGRES_PASSWORD: leon

volumes:
    postgres_data: