# Generated by Django 4.2.5 on 2023-09-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('head_direction', models.IntegerField()),
                ('airline_icao', models.CharField(max_length=3)),
                ('aircraft_icao', models.CharField(max_length=4)),
                ('departure_icao', models.CharField(max_length=4)),
                ('arrival_icao', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=20)),
                ('response', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
