# Generated by Django 4.2.5 on 2023-09-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='aircraft_icao',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='airline_icao',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='arrival_icao',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='departure_icao',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
