# Generated by Django 4.2.5 on 2023-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_api_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='head_direction',
            field=models.IntegerField(null=True),
        ),
    ]
