# Generated by Django 4.2.5 on 2023-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_api_head_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
