# Generated by Django 4.2.5 on 2023-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_api_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
